website/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100))
    password = db.Column(db.String(100))
    carts = db.relationship("Cart", backref="user", lazy=True)


class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    description = db.Column(db.String(100))
    items = db.relationship("Item", backref="cart", lazy=True)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))


class Item(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    url = db.Column(db.String(100))
    price = db.Column(db.Float)
    cart_id = db.Column(db.Integer, db.ForeignKey("cart.id"))

website/__init__.py
from flask import Flask
from .views import views
from .auth import auth
from .models import db, User
from flask_login import LoginManager
from os import path


def create_app():
    app = Flask(__name__)
    # Setup Configuration
    app.config.from_pyfile("config.py") 

    # Register Blueprints
    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    # Bind the database to the app
    db.init_app(app)
    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    return app


def create_database(app):
    if not path.exists("database.db"):
        db.create_all(app=app)
        print("Database created")
        print(db)

website/auth.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import login_user, logout_user
import flask_login
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User, db

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["POST", "GET"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        found_user = User.query.filter_by(email=email).first()

        if found_user:
            if check_password_hash(pwhash=found_user.password, password=password):
                flask_login.login_user(found_user, remember=True)
                flash("Login successful", "success")
                return redirect(url_for("views.home"))
            else:
                flash("There was an error", "error")
        else:
            flash("User not found")

    return render_template("login.html")


@auth.route("/sign-up", methods=["POST", "GET"])
def sign_up():
    if request.method == "POST":
        email = request.form.get("email")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        # Validate fields
        found_user = User.query.filter_by(email=email).first()
        if not email:
            flash("Please enter an email", "error")
        elif not password1:
            flash("Please enter a password", "error")
        elif not password2:
            flash("Please confirm your password", "error")
        elif found_user:
            flash("Email already in use", "error")
        elif len(email) > 100:
            flash("Email must be less than 100 characters")
        elif password1 != password2:
            flash("Passwords do not match", "error")
        else:
            new_user = User(email=email, password=generate_password_hash(
                password=password1, method="sha256"))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Account created", "success")
            return redirect(url_for("views.home"))

    return render_template("sign_up.html")


@auth.route("/logout")
def logout():
    flask_login.logout_user()
    return redirect(url_for("auth.login"))

website/views.py
from importlib.metadata import requires
import json
from flask import Blueprint, flash, render_template, request, jsonify, redirect, url_for, abort
from sqlalchemy import desc
from .models import Cart, db, Item
from flask_login import current_user, login_required
views = Blueprint("views", __name__)


@views.route("/", methods=["GET", "POST"])
def home():
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login"))

    if request.method == "POST":
        if "create" in request.form:
            name = request.form.get("name")
            description = request.form.get("description")
            if name and description:
                create_cart(name, description)
            else:
                if not name:
                    flash("Enter a name", "error")
                if not description:
                    flash("Enter a description", "error")

    return render_template("index.html", user=current_user)


@views.route("/create-cart")
@login_required
def create_cart(name, description):
    new_cart = Cart(name=name, description=description,
                    user_id=current_user.id)
    db.session.add(new_cart)
    db.session.commit()
    flash("Successfully added cart", "success")

    return redirect(url_for("views.home"))


@views.route("/edit-cart/<int:id>", methods=["POST", "GET"])
@login_required
def edit_cart(id):
    cart = Cart.query.get_or_404(id)

    if request.method == "POST":
        name = request.form.get("name")
        url = request.form.get("url")
        price = request.form.get("price")

        if name:
            new_item = Item(name=name, url=url, cart_id=cart.id, price=price)
            db.session.add(new_item)
            db.session.commit()
            flash("Successfully added item", "success")
        else:
            if not name:
                flash("Please enter a name for your item")

    return render_template("edit_cart.html", id=id, cart=cart, title="Edit")


@views.route("/delete-cart", methods=["POST"])
def delete_cart():
    body = json.loads(request.data)
    cartId = body["cartId"]
    cart = Cart.query.get(cartId)

    if cart and cart.user_id == current_user.id:
        db.session.delete(cart)
        db.session.commit()

    return jsonify({})


@views.route("/edit-item/<int:id>", methods=["POST"])
@login_required
def edit_item(id):
    item = Item.query.get(id)
    cart = Cart.query.get(item.cart_id)

    if cart.user_id == current_user.id:
        try:
            item.name = request.form.get("name")
            item.url = request.form.get("url")
            item.price = request.form.get(
                "price") if request.form.get("price") else 0
            db.session.commit()
        except:
            flash("That didn't work")
    else:
        abort(403)

    return redirect(url_for("views.edit_cart", id=item.cart_id))


@views.route("/delete-item", methods=["POST"])
def delete_item():
    body = json.loads(request.data)
    cartId = body["cartId"]
    itemId = body["itemId"]
    cart = Cart.query.get(cartId)
    item = Item.query.filter_by(id=itemId, cart_id=cartId).first()

    if item and cart.user_id == current_user.id:
        db.session.delete(item)
        db.session.commit()

    return jsonify({})

website/templates/about.html
{% extends "base.html" %} {% block title %} About {% endblock %} {% block
content %}
<h1>About</h1>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='styles/style.css')}}"
    />

    <meta charset="utf-8" />
    <title>
      {% block title %} 
        {% if title %} 
          {{title}} 
        {% else %} Unicart {% endif %}
      {% endblock %}
    </title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{url_for('views.home')}}">unicart</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
              <a class="nav-link active" href="{{url_for('views.home')}}" aria-current="page">
              Home</a>
              <a class="nav-link" href="{{url_for('auth.logout')}}"> Log Out </a>
            {% else %}
              <a class="nav-link" href="{{url_for('auth.login')}}"> Log In </a>
              <a class="nav-link" href="{{url_for('auth.sign_up')}}"> Sign Up </a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% for
    category, message in messages %} {% if category == "error" %}
    <div class="alert alert-danger" role="alert">{{ message }}</div>
    {% elif category == "success" %}
    <div class="alert alert-success" role="alert">{{ message }}</div>
    {% else %}
    <div class="alert alert-primary" role="alert">{{ message }}</div>
    {% endif %} {% endfor %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>

    <script src="{{url_for('static', filename='js/app.js')}}"></script>
  </body>
</html>

website/templates/edit_cart.html
{% extends "base.html" %} {% block content %}
<h1>Edit {{cart.name}}</h1>
<p>{{cart.description}}</p>

<div id="items" class="list-group">
  {% for item in cart.items|reverse %}

  <!-- Cart Item -->
  <div
    id="{{item.id}}"
    class="list-group-item-action list-group-item d-flex flex-row p-2"
  >
    <!-- Edit Form -->
    <div class="edit-form d-none flex-grow-1">
      <form
        action="{{url_for('views.edit_item', id=item.id)}}"
        class="d-flex flex-row"
        method="POST"
        autocomplete="off"
      >
        <input
          name="name"
          type="text"
          class="m-1 form-control"
          placeholder="Name"
          value="{{item.name}}"
        />
        <input
          name="url"
          type="text"
          class="m-1 form-control"
          placeholder="Link"
          value="{{item.url}}"
        />
        <input
          name="price"
          type="number"
          step="0.01"
          class="m-1 form-control"
          placeholder="Price"
          value="{{item.price}}"
        />

        <button
          type="submit"
          onclick="saveChanges({{item.id}})"
          class="m-1 btn btn-primary"
        >
          Save
        </button>

        <button
          type="button"
          class="m-1 btn btn-primary"
          onclick="closeEditForm({{item.id}})"
        >
          Close
        </button>
      </form>
    </div>

    <!-- Item Info -->
    <div class="item-info d-flex flex-row flex-fill">
      <div class="d-flex flex-row">
        <a class="m-1" href="{{item.url}}"> <h3>{{item.name}}</h3> </a>
        <h3 class="m-1">{{"$%.2f" | format(item.price)}}</h3>
      </div>
      <div class="ms-auto d-flex flex-row">
        <button
          onclick="editItem({{item.id}})"
          type="button"
          class="m-1 btn btn-primary"
        >
          Edit
        </button>
      </div>
    </div>
    <button
      id="deleteBtn"
      type="button"
      class="m-1 btn btn-danger"
      class="close-button"
      onclick="deleteCart({{cart.id}})"
    >
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  {% endfor %}

  <!-- Create Item -->
  <li class="p-2 list-group-item">
    <form method="POST" autocomplete="off">
      <div class="d-flex flex-row">
        <input
          name="name"
          type="text"
          class="m-1 form-control"
          placeholder="Name"
        />
        <input
          name="url"
          type="text"
          class="m-1 form-control"
          placeholder="Link"
        />
        <input
          name="price"
          type="text"
          class="m-1 form-control"
          placeholder="Price"
        />
        <button type="submit" class="m-1 btn btn-primary">Add</button>
      </div>
    </form>
  </li>
</div>

{% endblock %}

website/templates/index.html
{% extends "base.html" %} {% block title %} Home {% endblock %} {% block content
%}
<h1>Home</h1>
<p>{{ current_user.email }}</p>
<!-- Trigger Create Cart Modal -->
<button
  type="button"
  class="btn btn-primary mb-4"
  data-bs-toggle="modal"
  data-bs-target="#createCartModal"
>
  Create New Cart
</button>

<!-- Create Cart -->
<div
  class="modal fade"
  id="createCartModal"
  tabindex="-1"
  aria-labelledby="createCartModal"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createCart">Create Cart</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form id="create" method="POST">
          <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" name="name" id="name" />
            <label for="description">Description</label>
            <input
              type="text"
              class="form-control"
              name="description"
              id="description"
              placeholder="Optional"
            />
          </div>

          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-bs-dismiss="modal"
            >
              Close
            </button>
            <button name="create" type="submit" class="btn btn-primary">
              Create
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Cart list -->
<div id="carts" name="carts" class="list-group d-flex flex-column">
  {% for cart in user.carts %}

  <div id="{{cart.id}}" class="list-group-item list-group-item-action">
    <div class="d-flex">
      <div class="p-2"><h3>{{cart.name}}</h3></div>
      <div class="p-2">
        <h3>
          {%with price = cart.items | sum(attribute="price") %}
            {{"$%.2f"|format(price)}}
          {% endwith %}
        </h3>
      </div>
      <div class="ms-auto pt-2">
        <a
          class="btn btn-primary"
          href="{{url_for('views.edit_cart', id=cart.id)}}"
          id="editBtn"
          type="button"
        >
          Edit
        </a>

        <button
          id="deleteBtn"
          type="button"
          class="btn btn-danger"
          class="close-button"
          onclick="deleteCart({{cart.id}})"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>

    <div class="list-group d-flex flex-row">
      <small class="p-2">{{cart.description}}</small>
    </div>

    <!-- Cart items -->
    <div class="items d-none">
      <ul class="list-group list-group-horizontal">
        {% for item in cart.items %}
        <li class="list-group-item">
          <a class="link-primary" href="{{item.url}}">{{item.name}}</a>
        </li>
        {% endfor %}

        <!-- <li class="p-2 list-group-item">
          <div class="d-flex flex-row">
            <div id="addItem" class="d-flex flex-row d-none">
              <input
                name="name"
                type="text"
                class="m-1 form-control"
                placeholder="Name"
              />
              <input
                name="url"
                type="text"
                class="m-1 form-control"
                placeholder="Link"
              />
            </div>
            <button
              id="addButton"
              onclick="addItem({{cart.id}})"
              type="button"
              class="m-1 btn btn-primary"
            >
              Add
            </button>
          </div>
        </li> -->
      </ul>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %} Login {% endblock %} {% block
content %}
<h1>Login</h1>
<form method="POST">
  <div class="form-group">
    <label for="email">Email</label>
    <input type="email" class="form-control" id="email" name="email" />
  </div>

  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" id="password" name="password" />
  </div>

  <button type="submit" class="m-2 btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %} Sign Up {% endblock %} {% block
content %}
<h1>Sign Up</h1>
<form method="POST">
  <div class="form-group">
    <label for="email">Email</label>
    <input
      type="email"
      class="form-control"
      name="email"
      id="email"
      placeholder=""
    />
    <small>We'll never share your email with anyone else</small>
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      name="password1"
      id="password1"
      placeholder=""
    />
  </div>
  <div class="form-group">
    <label for="password2">Confirm password</label>
    <input
      type="password"
      class="form-control"
      name="password2"
      id="password2"
      placeholder=""
    />
  </div>
  <button type="submit" class="btn btn-primary">Sign Up</button>
</form>
{% endblock %}